### ISSUE TITLE
Using pillar.example as template difficulties

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/postgres-formula#156]
A few weeks back I tested installation of this formula on Fedora/Debian/OpenSUSE without pillars and this worked good.   Repeating this test "with pillars" using pillar.example as template was unsuccessful as many individual states failed.  I solved by including following in pillar.example.  

> postgres:
>   use_upstream_repo: False
>   version: '9.6'
> {% if salt['grains.get']('os_family') == 'RedHat' or salt['grains.get']('os') == 'SUSE' %}
>   pkgs_extra: [ postgresql-contrib, postgresql-plpython, postgresql-jdbc, postgresql-docs]
> {% elif salt['grains.get']('os_family') == 'Debian' %}
>   pkg: postgresql-9.6
>   pkgs_extra: [ postgresql-contrib, postgresql-plpython-9.6, libpostgresql-jdbc-java]
>   python: python-psycopg2
>   conf_dir: /var/lib/postgresql/data
>  postgresconf: ""
> {% endif %}
> 
>   prepare_cluster:
> {% if salt['grains.get']('os_family') == 'RedHat'  %}
>     command: /usr/bin/initdb --pgdata=/var/lib/pgsql/data
>     test: test -f /var/lib/pgsql/data/PG_VERSION
> {% elif salt['grains.get']('os') == 'SUSE' %}
>     command: /usr/lib/postgresql/9.6/bin/initdb --pgdata=/var/lib/pgsql/data
>     test: test -f /var/lib/pgsql/data/PG_VERSION
> {% elif salt['grains.get']('os_family') == 'Debian' %}
>     command: /usr/lib/postgresql/9.6/bin/initdb --pgdata=/var/lib/postgresql/data
>     test: test -f /var/lib/postgresql/data/PG_VERSION
> {% endif %}
>     user: postgres
>     env: {}

Should I raise PR to update pillar.example with same (perhaps commented out) as workaround to help others?

**Comment by EvaSDK** [comment]
Do I understand correctly that you just copied pillar.example into your pillars ? If so, this will not work for sure as it is only meant to show what can be configured, not to provide a working configuration.

**Comment by noelmcloughlin** [comment]
Yes I understand its a template.  However I could update pillar.example adding above as commented section showing example working pillars - because it took me quite a while to nail this.  So my question is whether you think this is worthwhile, if yes I'll do PR.  Thanks @EvaSDK

**Comment by EvaSDK** [comment]
Making the whole pillar.example be compatible with all supported distros does seem like an extensive maintenance work so I'd wouldn't recommend doing it, but I'm not the formula's maintainer :).

**Comment by noelmcloughlin** [comment]
I was thinking we add the support above but "commented out" ;-)

**Comment by noelmcloughlin** [comment]
@EvaSDK please review PR - I updated osmap.yaml instead.
