### ISSUE TITLE
Are custom data directories supported?

### ISSUE THREAD

**Issue by AndreiPashkin** [saltstack-formulas/postgres-formula#239]
Is it possible to specify custom data directory using the formula? Currently I get `"cluster configuration already exists"` error when `postgres:data_dir` is provided.

**Comment by noelmcloughlin** [comment]
Hi @AndreiPashkin there are few ways forward.

1. Run ``postgres.server.remove`` before ``postgres`` state
2. Set `postgres:data_dir` to unique value:  ``postgres:data_dir: /var/lib/mydir/mydata``

If both are not working then there is either bug or pillar data is wrong.
