### ISSUE TITLE
osFamilyMap.yaml FreeBSD default user

### ISSUE THREAD

**Issue by sticky-note** [saltstack-formulas/postgres-formula#263]
Actually default user for FreeBSD is `pgsql` whereas it is `postgres` on FreeBSD's package installation for Postgres 9.6.
It causes `postgres.server` state to fail without pillar adjustments.

**Comment by vutny** [comment]
@sticky-note Thanks for pointing us to it. Seems to be an easy fix. Would you mind to submit a PR?

**Comment by sticky-note** [comment]
I'm currently isolating a bug with the service. Don't know if it involves the formula or salt itself. I'll submit a PR when ready.
