### ISSUE TITLE
Default pg_hba.conf should not use "trust" directive

### ISSUE THREAD

**Issue by rhertzog** [saltstack-formulas/postgres-formula#28]
I see this in your pg_hba.conf:
```
# IPv4 local connections:
host all all 127.0.0.1/32 trust
# IPv6 local connections:
host all all ::1/128 trust
```

If I read this correctly, this means that any local user can connect as anyone else... the default value at least on Debian systems is to have "md5" instead of "trust" on those lines so that access over IP is password restricted. Please change this to a safer default and let people which want those unsafe rules add them themselves (through the postgres:acls pillar).

**Comment by mriedmann** [comment]
As I've seen this is solved in the current master-branch 
See: #30

**Comment by rhertzog** [comment]
Yeah, confirmed. Closing.
