### ISSUE TITLE
Do not install -dev packages by default, use a separate state or a pillar to enable that feature

### ISSUE THREAD

**Issue by rhertzog** [saltstack-formulas/postgres-formula#29]
Most Postgres servers do not need the development headers installed. On the contrary, installing those packages will bring a bunch of other unwanted packages (including a compiler).

One can work around this by setting the pillar "postgres:lookup:pkg_dev" to False but this does not look like the proper interface to make such a decision. Either you need a pillar "postgres:install_dev_packages" that would default to False or you put those states in a separate sls file (postgres/dev.sls).

Thank you for considering!

**Comment by rhertzog** [comment]
BTW the work-around above doesn't work as you also install libpq-dev unconditionally. :-(

**Comment by gravyboat** [comment]
This is fixed in #55 @rhertzog
