### ISSUE TITLE
Tablespaces support breaks backward compatibility

### ISSUE THREAD

**Issue by nicksloan** [saltstack-formulas/postgres-formula#48]
17baaa9 breaks backward compatibility by forcing a new key to be added to the pillar called tablespaces. This should definitely be defaulted to an empty dict in the state.

**Comment by gravyboat** [comment]
Thanks for the note @nicksloan. @iggy Do you already have a fix for this planned in your future stuff?

**Comment by gravyboat** [comment]
@nicksloan this is now fixed with #49. You should be good to go, thanks again for the report.

**Comment by iggy** [comment]
Sorry about that. I'll make sure I test that kind of thing next time.
