### ISSUE TITLE
Does not function from salt-call

### ISSUE THREAD

**Issue by joshland** [saltstack-formulas/postgres-formula#52]
I use salt-call and vagrant for various testing which I perform as I am developing salt states.  I am fairly new to the salt world, so occasionally I misunderstand what is happening.  When I tried to use this formula, from 'salt-call' in my salty vagrant, I get the following error:

```
[ERROR   ] Failed to read the virtual function for module: postgres_ext
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1072, in process_virtual
    virtual = mod.__virtual__()
  File "/var/cache/salt/minion/extmods/modules/postgres_ext.py", line 19, in __virtual__
    if 'postgres.psql_query' in __salt__:
NameError: global name '__salt__' is not defined
```

I found a few references to this, but https://github.com/saltstack/salt/issues/15616 appears to address this issue.   

Comments / Suggestions?

Edit: Version
salt 2014.7.3 (Helium)
Python 2.7.5
CentOS Linux release 7.0.1406 (Core) 

Just upgraded to v2014.7.5 - still broken.

**Comment by thomaschaaf** [comment]
I too get this error. I tried an older version (older then when postgres_ext.py) was added and that works.

**Comment by iggy** [comment]
What version of Salt are you guys running? (which btw is something you should include in every bug report ;)

**Comment by joshland** [comment]
I updated my original message with version information - I apologize that I forgot it.

**Comment by babilen** [comment]
@joshland Could you try it again with the current version? @iggy's PR just got merged.
