### ISSUE TITLE
Service not installed on CentOS 7

### ISSUE THREAD

**Issue by AusIV** [saltstack-formulas/postgres-formula#63]
On CentOS 7, the package that provides the server is postgresql-server, but only postgres is being installed. This means that the postgres user isn't being created, and the service isn't available to be enabled.

**Comment by iggy** [comment]
I'll look into this sometime this week.

**Comment by blast-hardcheese** [comment]
Just ran into this myself a couple weeks ago-- This is due to Cent packaging putting client binaries in the `postgresql` package, while the server is in `postgresql-server`:

```
# yum search postgresql
postgresql.x86_64 : PostgreSQL client programs
postgresql-contrib.x86_64 : Extension modules distributed with PostgreSQL
postgresql-devel.x86_64 : PostgreSQL development header files and libraries
postgresql-libs.x86_64 : The shared libraries required for any PostgreSQL clients
postgresql-server.x86_64 : The programs needed to create and run a PostgreSQL server
```

**Comment by blast-hardcheese** [comment]
Not sure if this changed in CentOS 7, and I don't have a CentOS 6 box still around to check.
