### ISSUE TITLE
Add conf_dir to pillar.example

### ISSUE THREAD

**Issue by danimbrogno** [saltstack-formulas/postgres-formula#66]
Noticed that you have "conf_dir" set in the defaults.yaml file, but this isn't overridden in the pillar.example file. I was getting errors related to the postgres.conf file not being found when I called state.highstate until I realized this had to be set in the postgres.sls pillar. In the interest of having sane defaults in pillar.example I'm suggesting this setting be added:

conf_dir: '/etc/postgresql/9.3/main'

**Comment by iggy** [comment]
What distro? It sounds like it should probably be something in the codenamemap or osmap.

**Comment by danimbrogno** [comment]
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-63-generic x86_64)

**Comment by SunPowered** [comment]
+1 The conf_dir for Ubuntu must be set explicitly.  This should be added to the osmap

**Comment by puneetk** [comment]
please send pull request with fixes, thank you :+1:

**Comment by abednarik** [comment]
This is already done https://github.com/saltstack-formulas/postgres-formula/commit/abd8314225792f519aab053e228dd213db777da0

Would be good to close this issue :)
