### ISSUE TITLE
Where would barman salt state go?

### ISSUE THREAD

**Issue by herisanu** [saltstack-formulas/postgres-formula#80]
Hi, 
we're using barman (http://www.pgbarman.org/) as a backup tool for postgres? Where would the barman state go? Would you accept a postgres.barman inside the current formula?

**Comment by masterkorp** [comment]
I think a separated formula would be the best.

**Comment by gravyboat** [comment]
Yeah I'd rather have another formula. I can create the repo if you want to work on it.

**Comment by herisanu** [comment]
That's ok, thanks.

**Comment by fr6nco** [comment]
Hi, is this formula finished?

**Comment by herisanu** [comment]
Hey @fr6nco , yes it is, but it's in the internal git repo.
I need to ask permission to share it on github. It's a simple install the package and create the configuration from jinja templates.

**Comment by fr6nco** [comment]
@herisanu thats great. Could you please ask, wether you can publish it? 

Or could you email me the source code zipped or targz-d ? 

Thank you

**Comment by herisanu** [comment]
Ok @fr6nco I'll ask my manager and reply.

**Comment by fr6nco** [comment]
Hi @herisanu, do you have any updates?
