### ISSUE TITLE
Formula will not work with 9.5

### ISSUE THREAD

**Issue by Routhinator** [saltstack-formulas/postgres-formula#89]
I'm opening this for users looking to use this module. Until the following bug in the postgres salt state is merged and rolled out to package repos, this formula with fail with 9.5:

https://github.com/saltstack/salt/issues/26845

**Comment by iggy** [comment]
We have copies of other states/modules in this formula, we could just pull over the fixed version for now.

**Comment by Neocid** [comment]
We have the same error here.

`Command '/usr/bin/psql --no-align --no-readline --no-password --dbname postgres -v datestyle=ISO,MDY -c \'COPY (SELECT pg_roles.rolname as "name",pg_roles.rolsuper as "superuser", pg_roles.rolinherit as "inherits privileges", pg_roles.rolcreaterole as "can create roles", pg_roles.rolcreatedb as "can create databases", pg_roles.rolcatupdate as "can update system catalogs", pg_roles.rolcanlogin as "can login", pg_roles.rolreplication as "replication", pg_roles.rolconnlimit as "connections", pg_roles.rolvaliduntil::timestamp(0) as "expiry time", pg_roles.rolconfig  as "defaults variables" FROM pg_roles) TO STDOUT WITH CSV HEADER\'' failed with return code: 1
[ERROR   ] stderr: ERROR:  column pg_roles.rolcatupdate does not exist`

**Comment by babilen** [comment]
I think @iggy's idea of simply backporting a fixed version of the respective modules would be a sane approach. Which version is needed?

@Neocid: Which version of Saltstack are you running on the minion?

**Comment by Neocid** [comment]
@babilen We use an old version which is now deprecated: 2015.5.3 (Lithium). We will try with the latest version.

**Comment by vutny** [comment]
The issue saltstack/salt#26845 has been fixed since Salt version `2015.8.4`.
Anyhow, it's really easy to obtain fixed `salt/modules/postgres.py` file and put it under your `salt://_modules/` custom modules directory to get this resolved.

I think this issue could be safely closed.

**Comment by babilen** [comment]
Thank you for the update, @vutny

**Comment by Neocid** [comment]
Thanks @vutny
